### ISSUE TITLE
SQLite3 database export?

### ISSUE THREAD

**Issue by EtherTyper** [sqle/gitql#91]
I think being able to export a db dump of all the [tables described in README.md](https://github.com/gitql/gitql#tables) would be very useful.

**Comment by smola** [comment]
@EtherTyper CSV output will come soon, see https://github.com/gitql/gitql/issues/82
I think that should be enough to export to other databases.

Anyway, we might accept contributions of functionality to get the output as a SQL dump.

**Comment by smola** [comment]
It is now possible to query tables with `SELECT * FROM <table>` and dump to a CSV or JSON file.
Closing this, since this is probably as far as we want to go for export. We might add a `dump` command to dump full databases at some point.

**Comment by EtherTyper** [comment]
@smola Cool! I'll try that out.
